---
output: github_document
---
<!-- README.md is generated from README.Rmd. Please edit that file -->

# `iProFun`

## An *i*ntegrative analysis tool to screen for *Pro*teogenomic *Fun*ctional traits perturbed by DNA copy number alterations (CNA) and DNA methylation


The goal of **iProFun** is to 

* characterize functional consequences of DNA copy number and methylation alterations in tumors 

* facilitate screening for cancer drivers contributing to tumor initiation and progression, since CNAs and DNA methylations that preserve functional consequences are more likely to be cancer drivers. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Installation

You can install:

* the most recent officially-released version from CRAN with

    ```R
    install.packages("iProFun")
    ````

* the latest development version from GitHub with

    ```R
    install.packages("devtools")
    devtools::install_github("sfirke/iProFun")
    ````
    
    
## iProFun Integrative analysis pipeline

Below is examples of how iProFun is commonly used.  A full description of the tool can be found in our MCP paper,

### Gene-level multiple linear regression to obtain summary statistics

### Primo – An integrative analysis method for detecting joint associations of DNA al- terations with multi-omics traits

### False discovery rate assessment